const obstacles = [
    [
        "xxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x        xxxxxxxxxxxxxxxxx           x",
        "x                                    x",
        "x                F                   x",
        "x                                    x",
        "x        xxxxxxxxxxxxxxxxx           x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                                    x",
        "x                        x           x",
        "x                        x           x",
        "xxxxxxxxxxxxxxxxxxxxxxxxxx           x",
    ],
    [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "x                               x",
        "x                               x",
        "x                           xxxxx",
        "x                                ",
        "x                                ",
        "x                                ",
        "x                                ",
        "x                                ",
        "x                                ",
        "xxxxxxxxx        xxxxxxxxxxxxxxxx",
        "x                x              x",
        "x                x              x",
        "x                x              x",
        "x                               x",
        "x                               x",
        "x                               x",
        "xxxxxxxxxxxxxxxxxxxxxx          x",
        "x                    x          x",
        "x                               x",
        "x        F                      x",
        "x                               x",
        "x                               x",
        "x                               x",
        "x                               x",
        "x                               x",
        "x                               x",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    ],
    [
        "xxxxxxxxxxxxxxxxxx",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "x             xxxx",
        "x                 ",
        "x                 ",
        "x                 ",
        "x                 ",
        "x                 ",
        "x                 ",
        "x                 ",
        "x                 ",
        "xxxxxxxxxxxxxxxxxx",
        "                 x",
        "                 x",
        "                 x",
        "                 x",
        "                 x",
        "                 x",
        "                 x",
        "                 x",
        "xxxx             x",
        "x                x",
        "x                x",
        "x                x",
        "x                x",
        "xxxxxxxxxxxxxxxxxx"
    ],
    [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxx",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x                                   x",
        "x       xxxxx                       x",
        "x       x   x                       x",
        "x       x   x                       x",
        "x       x   x                       x",
        "x       x   x                       x",
        "x       x   x                       x",
        "x       x   x                       x",
        "x       x   x                       x",
        "x       x   x                       x",
        "x       x   x                       x",
        "xxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx",    
    ]
];